### ISSUE TITLE
Date.parse returning NaN is not non-standard

### ISSUE THREAD

**Issue by evilpie** [compat-table/compat-table#1213]
Looking at the spec for [Date.parse](https://tc39.github.io/ecma262/#sec-date.parse):

> Unrecognizable Strings or dates containing illegal element values in the format String shall cause Date.parse to return NaN.

Maybe I am missing something or the spec just changed here.

**Comment by ljharb** [comment]
None of the [test cases](https://github.com/kangax/compat-table/blob/45059d27b42f7f64a721b47d2e54c19422e9beec/data-non-standard.js#L874-L877) contain illegal element values; the issue is that it's a correctly formatted date, which delegates to the preceding sentence:
> If the String does not conform to that format the function may fall back to any implementation-specific heuristics or implementation-specific date formats

**Comment by evilpie** [comment]
Okay I don't understand what this is meant to test. All of those dates parse as NaN in Firefox, so we don't seem to have those specific implementation-defined date formats at least.

**Comment by ljharb** [comment]
https://github.com/kangax/compat-table/blob/gh-pages/data-non-standard.js#L874 was broken on Firefox 3.6, and was fixed some time on or before v49.

**Comment by evilpie** [comment]
Sorry, I am totally confused by this. What are we trying to test here?

1. That Date.parse returns NaN for some strings, which is AFAIK allowed?
2. That some date strings can't be parsed?

something else?

**Comment by ljharb** [comment]
2 - that some Date strings can't be parsed. It's in the non-standard page because it "shouldn't" be parsed, but no spec demands that.

**Comment by evilpie** [comment]
Okay I guess that is fair. I am still not sure why Chrome passes this. They parse a lot more stuff than we do.

**Comment by afmenez** [comment]
Can you come up with any samples of strings that are invalid but allowed by Chrome?  You can easily write a PR for it...

**Comment by PMAX-Kevin-Ashley** [comment]
I'm a mere BA at a small medical software firm who happened upon this issue and have never PR'd before in my life....

"[a-zA-Z\s]*[0-9]{1,???}[\s]*" is a regex that should approximate an answer to your question, afmenez

anything like this passes in chrome and should probably never be considered valid dates unless that charstring conforms to a specific implemented date format ("MMM YY", for example).... then again, I'm sure truncating any alphabetic strings from the left of a potential date was useful for someone somewhere.... perhaps the who and how are not documented, but it seems like it would be intentional.
